http://localhost:5000

Accept: application/json;
Content-Type: application/json; charset=utf-8

POST /auth/signup
{
	"email" : "yuki@user.com",
	"phone" : "1111111111",
	"username" : "yukiCus",
	"password" : "123123",
	"role" : "CUSTOMER"
}

############################################

http://localhost:5000

Accept: application/json;
Content-Type: application/json; charset=utf-8

POST /auth/login
{
	"username" : "yuki14",
	"password" : "123123"
}

#############################################

http://localhost:5000

Accept: application/json;
Content-Type: application/json; charset=utf-8
authorization: 

POST /alley/new

#############################################

http://localhost:5000

Accept: application/json;
Content-Type: application/json; charset=utf-8
authorization: 

GET /alley/list

#############################################

http://localhost:5000

Accept: application/json;
Content-Type: application/json; charset=utf-8
authorization: 

POST /request
{
	"startTime" : "14:00",
	"endTime" : "15:00",
	"alleyId" : 8,
	"playerCount" : 7,
	"contactInfo" : "998-773-221",
	"date" : "21-02-2025"
}

#############################################

http://localhost:5000

Accept: application/json;
Content-Type: application/json; charset=utf-8
authorization: 

POST /owner/requests
{
	"alleyId" : 8
}

#############################################

http://localhost:5000

Accept: application/json;
Content-Type: application/json; charset=utf-8
authorization: 

POST /owner/approve
{
	"resId" : 26
}

#############################################

http://localhost:5000

Accept: application/json;
Content-Type: application/json; charset=utf-8
authorization:

POST /owner/reject
{
	"resId" : 23
}

#############################################

http://localhost:5000

Accept: application/json;
Content-Type: application/json; charset=utf-8
authorization: 

GET /slots
{
	"alleyId" : 8
}
