http://localhost:5000

Accept: application/json;
Content-Type: application/json; charset=utf-8

POST /auth/signup
{
	"email" : "yuki@dev.com",
	"phone" : "9999999999",
	"username" : "yukiMan",
	"password" : "123123",
	"role" : "MANAGER"
}

############################################

http://localhost:5000

Accept: application/json;
Content-Type: application/json; charset=utf-8

POST /auth/login
{
	"username" : "yukiCus",
	"password" : "123123"
}

#############################################

http://localhost:5000

Accept: application/json;
Content-Type: application/json; charset=utf-8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJiNzI0NjViLTJkYTctNDA0Yy1iYzU4LWFkNjc3ZDg0MmYyNSIsImlhdCI6MTczOTYyODM4MiwiZXhwIjoxNzM5NjU3MTgyfQ.Jo5QYuwZVQP1CWX9mzbG8eDGaG_PxBBPTkUspyqF0dM 

POST /alley/new

#############################################

http://localhost:5000

Accept: application/json;
Content-Type: application/json; charset=utf-8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJiNzI0NjViLTJkYTctNDA0Yy1iYzU4LWFkNjc3ZDg0MmYyNSIsImlhdCI6MTczOTYyODM4MiwiZXhwIjoxNzM5NjU3MTgyfQ.Jo5QYuwZVQP1CWX9mzbG8eDGaG_PxBBPTkUspyqF0dM 

GET /alley/list

#############################################

http://localhost:5000

Accept: application/json;
Content-Type: application/json; charset=utf-8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ2NzI0OGY3LWNmMDUtNDZiYS1hZWZhLWI3ZTI4ZjQwMjExZiIsImlhdCI6MTczOTYyODMxNywiZXhwIjoxNzM5NjU3MTE3fQ.b5ETM6NhtsQT_5EDfbYMfmlMOj1ItnhXqGw9lH8MVmU 

POST /request
{
	"startTime" : "17:00",
	"endTime" : "19:00",
	"alleyId" : 16,
	"playerCount" : 7,
	"contactInfo" : "998-773-221",
	"date" : "21-02-2025"
}

#############################################

http://localhost:5000

Accept: application/json;
Content-Type: application/json; charset=utf-8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJiNzI0NjViLTJkYTctNDA0Yy1iYzU4LWFkNjc3ZDg0MmYyNSIsImlhdCI6MTczOTYyODM4MiwiZXhwIjoxNzM5NjU3MTgyfQ.Jo5QYuwZVQP1CWX9mzbG8eDGaG_PxBBPTkUspyqF0dM  

POST /owner/requests
{
	"alleyId" : 16
}

#############################################

http://localhost:5000

Accept: application/json;
Content-Type: application/json; charset=utf-8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJiNzI0NjViLTJkYTctNDA0Yy1iYzU4LWFkNjc3ZDg0MmYyNSIsImlhdCI6MTczOTYyODM4MiwiZXhwIjoxNzM5NjU3MTgyfQ.Jo5QYuwZVQP1CWX9mzbG8eDGaG_PxBBPTkUspyqF0dM  

POST /owner/approve
{
	"resId" : 29
}

#############################################

http://localhost:5000

Accept: application/json;
Content-Type: application/json; charset=utf-8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJiNzI0NjViLTJkYTctNDA0Yy1iYzU4LWFkNjc3ZDg0MmYyNSIsImlhdCI6MTczOTYyODM4MiwiZXhwIjoxNzM5NjU3MTgyfQ.Jo5QYuwZVQP1CWX9mzbG8eDGaG_PxBBPTkUspyqF0dM

POST /owner/reject
{
	"resId" : 31
}

#############################################

http://localhost:5000

Accept: application/json;
Content-Type: application/json; charset=utf-8
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ2NzI0OGY3LWNmMDUtNDZiYS1hZWZhLWI3ZTI4ZjQwMjExZiIsImlhdCI6MTczOTYyODMxNywiZXhwIjoxNzM5NjU3MTE3fQ.b5ETM6NhtsQT_5EDfbYMfmlMOj1ItnhXqGw9lH8MVmU 
POST /slots
{
	"alleyId" : 16
}
